### PR TITLE
refactor: Split RUN block into multiple, smaller blocks

### PR DESCRIPTION
**Pull request by oprearocks**
This Docker to make use of its layer system and commit intermediary phases of the contianer build to FS.
In turn, whenever something fails when building the image, the whole process is not restarted from step 0.

Signed-off-by: Adrian Oprea <adrian@oprea.rocks>

### CODE REVIEW

**Comment by oprearocks** [comment]
So, the thing is that I ran out of resources multiple times, while building the image, and whenever I wanted to start over, the process would start at step 0. 

This is why I took the liberty to split the commands which were already grouped properly, into separate `RUN` blocks.

This allows Docker to commit intermediary versions of whatever it has successfully installed up to a point, and if the build fails at the last step, it is able to use the valid layers it has created and committed up to that point. 

See https://docs.docker.com/engine/reference/builder/#run for reference
> The RUN instruction will execute any commands in a new layer on top of the current image and commit the results. The resulting committed image will be used for the next step in the Dockerfile.
>
> Layering RUN instructions and generating commits conforms to the core concepts of Docker where commits are cheap and containers can be created from any point in an image’s history, much like source control.

**Review by defconst — COMMENTED** [review]
I `cherry-pick`ed most changes to branch `develop`. Thanks!

**Comment by defconst** [comment]
294efe2930861bc2b4a5be4b4e28df0ccdb4f857 and ed441e4c43e70c2d2d2f80aef8f42fda573b568c now in `develop`

**Comment by oprearocks** [comment]
Thanks a lot @defconst ! Glad I could help.

**Pull request closed without merging**
